# Generated by Django 4.1.6 on 2023-02-16 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 16), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='distributionlist',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время рассылки'),
        ),
    ]
